services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    environment:
      - PORT=${PORT:-10000}
    ports:
      - "${PORT:-10000}:${PORT:-10000}"
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - ushort
  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - ushort

networks:
  ushort:
    name: ushort
