services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    environment:
      - PORT=${PORT:-10000}
    ports:
      - "${PORT:-10000}:${PORT:-10000}"
    restart: unless-stopped
    networks:
      - ushort

  redis:
    image: redis:latest
    restart: unless-stopped
    networks:
      - ushort

networks:
  ushort:
    name: ushort
