services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    environment:
      - PORT=${PORT:-8080}
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    restart: unless-stopped
    networks:
      - ushort

  redis:
    image: redis:latest
    restart: unless-stopped
    networks:
      - ushort

networks:
  ushort:
    name: ushort
